### PR TITLE
lcd: fix incompatible feature

### LINKED ISSUE #240: Compilation error on ESP IDF 5.0.4 (BSP-410)
After merging https://github.com/espressif/esp-bsp/pull/232 I cannot build application on ESP IDF 5.0.4.
Looks like the problem with condition - https://github.com/espressif/esp-bsp/blob/21277f5f1e9103eb2d08e900d410d4c295f98b04/components/lcd/esp_lcd_ili9341/esp_lcd_ili9341.c#L64
The line should be `#if ESP_IDF_VERSION <= ESP_IDF_VERSION_VAL(5, 0, 4)`

@Lzw655 ^

### LINKED ISSUE #242: Compilation error with ESP IDF 5.1.1
I used the previous version with ESP IDF 5.1.1 and had no problem. After updating to 1.1.0, I get these error messages:

> esp_lcd_st7796.c:77:29: error: 'esp_lcd_panel_dev_config_t' has no member named 'rgb_ele_order'
> esp_lcd_st7796.c:78:10: error: 'LCD_RGB_ELEMENT_ORDER_RGB' undeclared (first use in this function)

I checked esp_lcd_panel_dev_config_t in ESP IDF and in fact it doesn't have such a member.

### PR DESCRIPTION
**Pull request by Lzw655**
# ESP-BSP Pull Request checklist

> Note: For new BSPs create a PR with this [link](https://github.com/espressif/esp-bsp/compare/main...my-branch?quick_pull=1&template=pr_template_bsp.md).

- [x] Version of modified component bumped
- [x] CI passing

# Change description
* replace `rgb_ele_order` with `rgb_endian`
* add more idf version check
* closes #240 
* closes #242

### CODE REVIEW

File: components/lcd/esp_lcd_ili9341/include/esp_lcd_ili9341.h [hunk 1]
```diff
@@ -57,13 +57,25 @@ typedef struct {
...
  */
+#if ESP_IDF_VERSION < ESP_IDF_VERSION_VAL(5, 0, 4)
+#define ILI9341_PANEL_BUS_SPI_CONFIG(sclk, mosi)        \
+    {                                                   \
+        .sclk_io_num = sclk,                            \
+        .mosi_io_num = mosi,                            \
+        .miso_io_num = -1,                              \
+        .quadhd_io_num = -1,                            \
+        .quadwp_io_num = -1,                            \
+        .max_transfer_sz = SPI_LL_DATA_MAX_BIT_LEN >> 3,\
```
Comment (espzav) [inline components/lcd/esp_lcd_ili9341/include/esp_lcd_ili9341.h:76]: Please, did you try on IDF4.4? The `SPI_LL_DATA_MAX_BIT_LEN` not exists in IDF4.4.  I think, that we shouldn't use this constant.

Comment (Lzw655) [reply components/lcd/esp_lcd_ili9341/include/esp_lcd_ili9341.h:76]: You're right. So I added the following check before this macro:
```c
#if ESP_IDF_VERSION >= ESP_IDF_VERSION_VAL(4, 4, 2)
```

Comment (espzav) [reply components/lcd/esp_lcd_ili9341/include/esp_lcd_ili9341.h:76]: Oh, I see. But I am trying on the latest IDF4.4.6 and it is not working there. Compilation failed.

Comment (Lzw655) [reply components/lcd/esp_lcd_ili9341/include/esp_lcd_ili9341.h:76]: Oh my god, I tested it from v4.4 to v4.4.5, but only missed v4.4.6. I'll just make it available only after v5.0.4.

Comment (espzav) [reply components/lcd/esp_lcd_ili9341/include/esp_lcd_ili9341.h:76]: What about to put there `#if ESP_IDF_VERSION >= ESP_IDF_VERSION_VAL(5, 0, 0)` ?
And I don't see diferencies after condition: `#if ESP_IDF_VERSION < ESP_IDF_VERSION_VAL(5, 0, 4)`

Comment (espzav) [reply components/lcd/esp_lcd_ili9341/include/esp_lcd_ili9341.h]: My recommendation:
No ifdefs and only one for all versions:
```
#define ILI9341_PANEL_BUS_SPI_CONFIG(sclk, mosi, max_transfer_sz)        \
    {                                                   \
        .sclk_io_num = sclk,                            \
        .mosi_io_num = mosi,                            \
        .miso_io_num = -1,                              \
        .quadhd_io_num = -1,                            \
        .quadwp_io_num = -1,                            \
        .max_transfer_sz = max_transfer_sz,\
    }
```

I would like to remove this include: `#include "hal/spi_ll.h"`

Comment (Lzw655) [reply components/lcd/esp_lcd_ili9341/include/esp_lcd_ili9341.h]: > What about to put there `#if ESP_IDF_VERSION >= ESP_IDF_VERSION_VAL(5, 0, 0)` ? And I don't see diferencies after condition: `#if ESP_IDF_VERSION < ESP_IDF_VERSION_VAL(5, 0, 4)`

In my test, the `SPI_LL_DATA_MAX_BIT_LEN ` exists in v5.0 ~ v5.0.3, and it is replaced by `SPI_LL_DMA_MAX_BIT_LEN` since v5.0.4.

Comment (Lzw655) [reply components/lcd/esp_lcd_ili9341/include/esp_lcd_ili9341.h]: > My recommendation: No ifdefs and only one for all versions:
> 
> ```
> #define ILI9341_PANEL_BUS_SPI_CONFIG(sclk, mosi, max_transfer_sz)        \
>     {                                                   \
>         .sclk_io_num = sclk,                            \
>         .mosi_io_num = mosi,                            \
>         .miso_io_num = -1,                              \
>         .quadhd_io_num = -1,                            \
>         .quadwp_io_num = -1,                            \
>         .max_transfer_sz = max_transfer_sz,\
>     }
> ```
> 
> I would like to remove this include: `#include "hal/spi_ll.h"`

Yeah, it would be more easy. However, this macro is designed to minimize the number of input parameters, so that users don't need to worry about unnecessary configurations. And I think it can also remind users the `max_transfer_sz ` is limited by `SPI_LL_DMA_MAX_BIT_LEN`.

Comment (espzav) [reply components/lcd/esp_lcd_ili9341/include/esp_lcd_ili9341.h]: I understand, but the maximum can be different by this: https://github.com/espressif/esp-idf/blob/b4268c874a4cf8fcf7c0c4153cffb76ad2ddda4e/components/driver/spi/gpspi/spi_master.c#L1190 for DMA an non-DMA. 
As I remember right, I wanted to use this macro (`SPI_LL_DMA_MAX_BIT_LEN`) in past and here is the conversation with morris: https://gitlab.espressif.cn:6688/espressif/esp-idf/-/merge_requests/23199#note_1077058

Comment (Lzw655) [reply components/lcd/esp_lcd_ili9341/include/esp_lcd_ili9341.h]: Get it. I'll use the ``#define ILI9341_PANEL_BUS_SPI_CONFIG(sclk, mosi, max_transfer_sz) `` way. Thanks for your notice!

File: components/lcd/esp_lcd_gc9503/idf_component.yml [hunk 2]
```diff
@@ -1,8 +1,8 @@
-version: "2.1.0"
+version: "3.0.0"
 targets:
   - esp32s3
 description: ESP LCD GC9503
 url: https://github.com/espressif/esp-bsp/tree/master/components/lcd/esp_lcd_gc9503
 dependencies:
-  idf: ">=5.0.4"
```
Comment (Lzw655) [inline components/lcd/esp_lcd_gc9503/idf_component.yml:7]: @espzav I also make a change here. Because it relies on a new feature of IDF release/v5.0/v5.1 and master. PTAL!

Comment (Lzw655) [inline components/lcd/esp_lcd_gc9503/idf_component.yml:7]: @espzav I also make a change here. Because it relies on a new feature of IDF release/v5.0/v5.1 and master. PTAL!

File: components/lcd/esp_lcd_gc9503/idf_component.yml [hunk 3]
```diff
@@ -1,8 +1,8 @@
...
+  idf: ">5.0.4,!=5.1.1"
```
Comment (Lzw655) [inline components/lcd/esp_lcd_gc9503/idf_component.yml:7]: @espzav I also make a change here. Because it relies on a new feature of IDF release/v5.0/v5.1 and master. PTAL!

Comment (espzav) [reply components/lcd/esp_lcd_gc9503/idf_component.yml:7]: @Lzw655 thank you for changes. I have never seen this rule. Is it really working?

Comment (Lzw655) [reply components/lcd/esp_lcd_gc9503/idf_component.yml:7]: Yeah, now I can only use it in the master branch (v5.2). Otherwise, it will show version dependency errors.

**Review by espzav — APPROVED** [review]
@Lzw655 Thank you for fixes and changes! LGTM

File: components/lcd/esp_lcd_gc9a01/include/esp_lcd_gc9a01.h [hunk 4]
```diff
@@ -62,16 +62,17 @@ esp_err_t esp_lcd_new_panel_gc9a01(const esp_lcd_panel_io_handle_t io, const esp
...
  */
-#define GC9A01_PANEL_BUS_SPI_CONFIG(sclk, mosi)         \
-    {                                                   \
-        .sclk_io_num = sclk,                            \
-        .mosi_io_num = mosi,                            \
-        .miso_io_num = -1,                              \
-        .quadhd_io_num = -1,                            \
-        .quadwp_io_num = -1,                            \
-        .max_transfer_sz = SPI_LL_DMA_MAX_BIT_LEN >> 3, \
+#define GC9A01_PANEL_BUS_SPI_CONFIG(sclk, mosi, max_trans_sz)   \
```
Comment (igrr) [inline components/lcd/esp_lcd_gc9a01/include/esp_lcd_gc9a01.h:68]: @Lzw655 @espzav Adding another parameter looks like a breaking API change. Should the version be changed to 2.0.0 instead of 1.2.0?

Comment (Lzw655) [reply components/lcd/esp_lcd_gc9a01/include/esp_lcd_gc9a01.h:68]: Oh, I thought it didn't need to be changed since the 1.1.0 version has been marked yanked.

Comment (Lzw655) [reply components/lcd/esp_lcd_gc9a01/include/esp_lcd_gc9a01.h:68]: @igrr Can we remove the 1.1.0 version from the ESP Registry?

Comment (igrr) [reply components/lcd/esp_lcd_gc9a01/include/esp_lcd_gc9a01.h:68]: @tore-espressif Could you please help with this?

Comment (tore-espressif) [reply components/lcd/esp_lcd_gc9a01/include/esp_lcd_gc9a01.h:68]: >  I thought it didn't need to be changed since the 1.1.0 version has been marked yanked.

Breaking changes are allowed only between major releases, eg. 1.1.0 -> 2.0.0.

> Can we remove the 1.1.0 version from the ESP Registry?

1.1.0 was yanked. We want to avoid deleting broken versions, to keep sync between git and component-registry.

@Lzw655 Ideally, you can push a fix that would garantuee compatibility -> 1.2.1. Or we can re-release this as 2.0.0

Comment (Lzw655) [reply components/lcd/esp_lcd_gc9a01/include/esp_lcd_gc9a01.h:68]: > > I thought it didn't need to be changed since the 1.1.0 version has been marked yanked.
> 
> Breaking changes are allowed only between major releases, eg. 1.1.0 -> 2.0.0.
> 
> > Can we remove the 1.1.0 version from the ESP Registry?
> 
> 1.1.0 was yanked. We want to avoid deleting broken versions, to keep sync between git and component-registry.
> 
> @Lzw655 Ideally, you can push a fix that would garantuee compatibility -> 1.2.1. Or we can re-release this as 2.0.0

Ok, I will submit a PR to bump their versions to 2.0.0.
