### PR TITLE
fix(esp_lcd_touch_cst816s): Fixed compilation error for IDF5.1 and lower

### PR DESCRIPTION
**Pull request by espzav**
# ESP-BSP Pull Request checklist

- [x] Version of modified component bumped
- [x] CI passing
## Related
Caused by #470
# Change description
- Fixed IFD5.1 compilation issue in CST816S touch controller driver
- We need to CI tests for all components, which aren't used in BSPs. Because we need test it for all IDF versions before merge PR!

### CODE REVIEW

**Comment by espzav** [comment]
@tore-espressif PTAL

**Review by tore-espressif — APPROVED** [review]
